version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./runtime/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - proj-net
  app:
    build: ./docker/
    environment:
      YII_ENV: '${YII_ENV}'
      YII_DEBUG: '${YII_DEBUG}'
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/local-conf.d/:/usr/local/etc/php/local-conf.d/
    depends_on:
      - db
    ports:
        - "8080:8080"
    networks:
      - proj-net
  db:
    image: 'postgres:15.4'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql-database:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    networks:
      - proj-net

networks:
  proj-net:

volumes:
  pgsql-database:
    driver: local
