create table institutions
(
    id              integer generated by default as identity,
    name            text  not null,
    study_direction text  not null,
    education_form  text  not null,
    duration        real  not null,
    cost            money not null
);

alter table institutions
    add constraint institutions_pk
        primary key (id);

alter table institutions
    add constraint institutions_uk_name
        unique (name);


